-- Arena BMW X1 2012 — banco central
-- Execute no SQL Editor do projeto Supabase.
create table if not exists public.xp_sales (
  id bigint generated by default as identity primary key,
  sale_date date not null,
  captador text,
  promoter text,
  liner text,
  closer text,
  vgv numeric not null default 0,
  status text,
  source_key text unique,
  created_at timestamptz not null default now()
);

create table if not exists public.xp_adjustments (
  person_id text primary key,
  person_name text not null,
  role text not null,
  faltas integer not null default 0 check (faltas >= 0),
  atrasos integer not null default 0 check (atrasos >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.xp_bonuses (
  id bigint generated by default as identity primary key,
  person_id text not null,
  person_name text not null,
  role text,
  event_date date not null,
  xp bigint not null default 0,
  reason text not null,
  created_at timestamptz not null default now()
);

alter table public.xp_sales enable row level security;
alter table public.xp_adjustments enable row level security;
alter table public.xp_bonuses enable row level security;

drop policy if exists "arena read sales" on public.xp_sales;
drop policy if exists "arena insert sales" on public.xp_sales;
drop policy if exists "arena read adjustments" on public.xp_adjustments;
drop policy if exists "arena insert adjustments" on public.xp_adjustments;
drop policy if exists "arena update adjustments" on public.xp_adjustments;
drop policy if exists "arena read bonuses" on public.xp_bonuses;
drop policy if exists "arena insert bonuses" on public.xp_bonuses;

create policy "arena read sales" on public.xp_sales for select to anon using (true);
create policy "arena insert sales" on public.xp_sales for insert to anon with check (true);
create policy "arena read adjustments" on public.xp_adjustments for select to anon using (true);
create policy "arena insert adjustments" on public.xp_adjustments for insert to anon with check (true);
create policy "arena update adjustments" on public.xp_adjustments for update to anon using (true) with check (true);
create policy "arena read bonuses" on public.xp_bonuses for select to anon using (true);
create policy "arena insert bonuses" on public.xp_bonuses for insert to anon with check (true);
