/* Arena BMW X1 2012 — motor completo */
(()=>{
'use strict';
const CFG=window.SUPABASE_CONFIG||{}; const START='2026-07-01', DAY=50000;
const RATE={Captador:1400,Liner:1200,Closer:1000,Promotor:1400};
let sales=[],people=[],adjustments=[],bonuses=[],currentRole='Todos';
const $=id=>document.getElementById(id), num=v=>Number(v)||0;
const fmt=v=>new Intl.NumberFormat('pt-BR').format(Math.round(num(v)));
const brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(num(v));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/\s+/g,' ').toUpperCase();
const id=(r,n)=>r+':'+norm(n); const today=()=>new Date().toISOString().slice(0,10);
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}; const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const toast=t=>{const e=$('toast');if(e){e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2500)}};
function days(){const a=new Date(START+'T00:00:00'),b=new Date(today()+'T00:00:00');return Math.max(1,Math.floor((b-a)/86400000)+1)}
function rebuild(){const m=new Map();sales.forEach(s=>[['Captador',s.captador],['Liner',s.liner],['Closer',s.closer],['Promotor',s.promoter]].forEach(([role,name])=>{if(name&&norm(name)&&!['NAO INFORMADO','N/A','NAO'].includes(norm(name))){const k=id(role,name);if(!m.has(k))m.set(k,{id:k,name:String(name).trim(),role})}}));people=[...m.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))}
function adj(p){return adjustments.find(x=>x.person_id===p.id)||{faltas:0,atrasos:0}}
function stats(p){let vgv=0,casais=0;for(const s of sales){const owner=p.role==='Captador'?s.captador:p.role==='Liner'?s.liner:p.role==='Closer'?s.closer:s.promoter;if(norm(owner)!==norm(p.name))continue;if(/CANCEL|INATIV|CANCELAD/i.test(String(s.status||'')))continue;vgv+=num(s.vgv);casais++}const a=adj(p),max=days()*DAY,pres=Math.max(0,max-num(a.faltas)*DAY),pont=Math.max(0,max-num(a.atrasos)*DAY);const xpProd=Math.round(vgv/1000*(RATE[p.role]||0));const xpBonus=bonuses.filter(x=>x.person_id===p.id).reduce((z,x)=>z+num(x.xp),0);return {...p,vgv,casais,xpProd,xpPresenca:pres,xpPontualidade:pont,xpDisc:pres+pont,xpBonus,faltas:num(a.faltas),atrasos:num(a.atrasos),xp:xpProd+pres+pont+xpBonus}}
function rank(role=currentRole){return people.filter(p=>role==='Todos'||p.role===role).map(stats).sort((a,b)=>b.xp-a.xp||b.vgv-a.vgv||a.name.localeCompare(b.name,'pt-BR'))}
async function api(table,method='GET',body=null,query=''){if(!CFG.url||!CFG.anonKey)throw Error('Supabase não configurado');const u=CFG.url.replace(/\/$/,'')+'/rest/v1/'+table+(query?'?'+query:'');const r=await fetch(u,{method,headers:{apikey:CFG.anonKey,Authorization:'Bearer '+CFG.anonKey,'Content-Type':'application/json',Prefer:'return=representation,resolution=merge-duplicates'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.status===204?[]:await r.json()}
async function syncAdjust(p){const a=adj(p),row={person_id:p.id,person_name:p.name,role:p.role,faltas:Math.max(0,num($('adminFaltas').value)),atrasos:Math.max(0,num($('adminAtrasos').value)),updated_at:new Date().toISOString()};adjustments=adjustments.filter(x=>x.person_id!==p.id);adjustments.push(row);put('arena_adjustments',adjustments);if(CFG.url&&CFG.anonKey)await api('xp_adjustments','POST',row);render();toast('Faltas e atrasos salvos')}
async function bonus(){const p=people.find(x=>x.id===$('adminPerson').value),xp=num($('bonusXp').value),reason=$('bonusReason').value.trim();if(!p||!xp||!reason)return toast('Informe XP e motivo');const row={person_id:p.id,person_name:p.name,role:p.role,event_date:$('adminDate').value||today(),xp,reason};bonuses.push(row);put('arena_bonuses',bonuses);try{if(CFG.url&&CFG.anonKey)await api('xp_bonuses','POST',row)}catch(e){toast('Bônus salvo localmente; '+e.message)}$('bonusXp').value='';$('bonusReason').value='';render();toast('Bônus adicionado')}
function render(){const r=rank(),totalV=r.reduce((a,p)=>a+p.vgv,0);$('sourceInfo').textContent=(CFG.url?'🟢 Supabase conectado':'🟠 Modo local')+' • campanha desde 01/07/2026';$('cards').innerHTML=[['PROFISSIONAIS',r.length],['VGV',brl(totalV)],['XP TOTAL',fmt(r.reduce((a,p)=>a+p.xp,0))],['REGISTROS',fmt(sales.length)],['XP DISCIPLINA',fmt(r.reduce((a,p)=>a+p.xpDisc,0))],['FALTAS',fmt(r.reduce((a,p)=>a+p.faltas,0))]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('');$('top3').innerHTML=r.slice(0,3).map((p,i)=>`<div class="podium ${i===0?'first':''}"><div class="medal">${['🥇','🥈','🥉'][i]}</div><div class="pname">${p.name}</div><div class="muted">${p.role}</div><div class="bigxp">${fmt(p.xp)} XP</div></div>`).join('')||'<div class="notice">Nenhum resultado.</div>';const opts=people.map(p=>`<option value="${p.id}">${p.name} — ${p.role}</option>`).join('');['focusPerson','evoPerson','adminPerson'].forEach(k=>{const e=$(k);if(e){const old=e.value;e.innerHTML=opts;if([...e.options].some(o=>o.value===old))e.value=old}});focus();table();presence();admin();monthly();evolution()}
function focus(){const e=$('focusPerson');if(!e)return;const r=rank(),i=r.findIndex(p=>p.id===e.value);if(i<0){$('focus').innerHTML='<div class="notice">Nenhum profissional.</div>';return}const p=r[i],next=r[i-1];$('focus').innerHTML=`<div class="metricgrid"><div class="metric">Posição<b>#${i+1}</b></div><div class="metric">XP total<b>${fmt(p.xp)}</b></div><div class="metric">VGV<b>${brl(p.vgv)}</b></div><div class="metric">Presença<b>${fmt(p.xpPresenca)}</b></div><div class="metric">Pontualidade<b>${fmt(p.xpPontualidade)}</b></div><div class="metric">Faltas/Atrasos<b>${p.faltas} / ${p.atrasos}</b></div></div><div class="notice" style="margin-top:10px">${next?`Faltam <b>${fmt(Math.max(1,next.xp-p.xp+1))} XP</b> para ultrapassar ${next.name}.`:'🏆 TOP 1'}</div>`}
function table(){const role=$('rankRole')?.value||currentRole,q=norm($('search')?.value||''),all=rank(role),r=all.filter(p=>!q||norm(p.name).includes(q));$('rankingTable').innerHTML=r.map(p=>{const i=all.findIndex(x=>x.id===p.id);return `<tr><td>${i+1}</td><td>${i<3?['🥇','🥈','🥉'][i]:'—'}</td><td><b>${p.name}</b></td><td>${p.role}</td><td>${brl(p.vgv)}</td><td>${p.casais}</td><td>${fmt(p.xpProd)}</td><td>${fmt(p.xpDisc)}</td><td>${fmt(p.xpBonus)}</td><td><b>${fmt(p.xp)}</b></td><td>${p.faltas}</td></tr>`}).join('')}
function monthly(){const m=today().slice(0,7);$('monthTable').innerHTML=rank().map((p,i)=>{const b=bonuses.filter(x=>x.person_id===p.id&&String(x.event_date).startsWith(m)).reduce((z,x)=>z+num(x.xp),0);return `<tr><td>${i+1}</td><td>${p.name}</td><td>${p.role}</td><td>${fmt(p.xpDisc)}</td><td>${fmt(b)}</td><td><b>${fmt(p.xp)}</b></td></tr>`}).join('')}
function evolution(){const p=people.find(x=>x.id===$('evoPerson')?.value);if(!p)return;$('evoSummary').innerHTML=`<div class="metricgrid"><div class="metric">VGV<b>${brl(stats(p).vgv)}</b></div><div class="metric">XP produção<b>${fmt(stats(p).xpProd)}</b></div><div class="metric">XP disciplina<b>${fmt(stats(p).xpDisc)}</b></div><div class="metric">XP bônus<b>${fmt(stats(p).xpBonus)}</b></div></div>`;$('evoLog').innerHTML=`<div class="log-item">Desde 01/07/2026 • ${stats(p).faltas} falta(s) • ${stats(p).atrasos} atraso(s) • <b>${fmt(stats(p).xp)} XP</b></div>`}
function presence(){const d=$('attDate')?.value||today();$('attTable').innerHTML=people.map(p=>{const s=stats(p);return `<tr><td>${p.name}</td><td>${p.role}</td><td>${s.faltas?'❌ '+s.faltas+' falta(s)':'✅ Completa'}</td><td>${s.atrasos?'⌛ '+s.atrasos+' atraso(s)':'✅ Completa'}</td><td>${fmt(s.xpDisc)}</td></tr>`}).join('')}
function admin(){const p=people.find(x=>x.id===$('adminPerson')?.value);if(!p)return;const a=adj(p);$('adminFaltas').value=a.faltas||0;$('adminAtrasos').value=a.atrasos||0;$('adminLog').innerHTML=rank().map(x=>`<div class="log-item"><b>${x.name}</b> • ${x.role} • Faltas: ${x.faltas} • Atrasos: ${x.atrasos} • Disciplina: ${fmt(x.xpDisc)} XP</div>`).join('')}
function parse(text){const first=text.split(/\r?\n/,1)[0]||'',d=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';let rows=[],row=[],c='',q=false;for(let i=0;i<text.length;i++){let x=text[i],n=text[i+1];if(x==='"'&&q&&n==='"'){c+='"';i++;continue}if(x==='"'){q=!q;continue}if(x===d&&!q){row.push(c);c='';continue}if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&n==='\n')i++;row.push(c);if(row.some(v=>v.trim()))rows.push(row);row=[];c='';continue}c+=x}if(c||row.length){row.push(c);rows.push(row)}return rows}
function clean(s){return norm(s).replace(/^\uFEFF/,'')};function date(v){v=String(v||'').trim();let m=v.match(/(\d{2})[\/-](\d{2})[\/-](\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:v.slice(0,10)}function money(v){return Number(String(v||'0').replace(/[^0-9,.-]/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'))||0}
async function importCSV(file){const rows=parse(await file.text());if(!rows.length)return toast('CSV vazio');const h=rows.shift().map(clean), val=(o,...names)=>{for(const x of names){const v=o[clean(x)];if(v!==undefined)return v}return ''};const mapped=rows.map((r,i)=>{const o=Object.fromEntries(h.map((x,j)=>[x,String(r[j]??'').trim()]));return{sale_date:date(val(o,'DATA DE ATENDIMENTO','DATA/HORA DO CADASTRO','DATA'),),captador:val(o,'CAPTADOR'),promoter:val(o,'PROMOTOR DE MARKETING','PROMOTOR'),liner:val(o,'LINER','CONSULTOR'),closer:val(o,'CLOSER'),vgv:money(val(o,'VALOR VENDIDO','VGV','VALOR')),status:val(o,'STATUS DO CONTRATO','STATUS'),source_key:[i,val(o,'DATA','DATA DE ATENDIMENTO'),val(o,'NOME 1'),val(o,'NOME 2'),val(o,'VALOR VENDIDO')].join('|')}}).filter(x=>x.sale_date>=START);if(!mapped.length)return toast('Nenhum registro desde 01/07/2026');sales=mapped;put('arena_sales',sales);rebuild();if(CFG.url&&CFG.anonKey){try{await api('xp_sales','POST',mapped)}catch(e){toast('Base local atualizada; Supabase: '+e.message)}}render();toast(`${mapped.length} registros importados desde 01/07/2026`)}
async function load(){sales=get('arena_sales',[]);adjustments=get('arena_adjustments',[]);bonuses=get('arena_bonuses',[]);if(CFG.url&&CFG.anonKey){try{const [s,a,b]=await Promise.all([api('xp_sales','GET',null,'select=*'),api('xp_adjustments','GET',null,'select=*'),api('xp_bonuses','GET',null,'select=*')]);if(s?.length)sales=s;if(a)adjustments=a;if(b)bonuses=b}catch(e){console.warn('Supabase:',e.message)}}rebuild();render()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(b.dataset.view)?.classList.remove('hidden');document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{currentRole=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});['rankRole','search','focusPerson','evoPerson','adminPerson','attDate'].forEach(k=>$(k)?.addEventListener('input',render));$('saveAdjustments')?.addEventListener('click',async()=>{const p=people.find(x=>x.id===$('adminPerson').value);if(!p)return toast('Selecione uma pessoa');try{await syncAdjust(p)}catch(e){toast('Erro ao salvar no Supabase: '+e.message)}});$('bonusSave')?.addEventListener('click',bonus);$('dataFile')?.addEventListener('change',e=>e.target.files[0]&&importCSV(e.target.files[0]));}
window.addBonus=bonus;window.setStatus=()=>{};window.setFullDay=()=>{};document.addEventListener('DOMContentLoaded',()=>{bind();load()});
})();
