/* Arena BMW X1 2012 — motor da campanha */
(()=>{
'use strict';
const CFG=window.SUPABASE_CONFIG||{url:'',anonKey:''};
const START='2026-07-01',DAY_XP=50000;
const RATE={Captador:1400,Liner:1200,Closer:1000,Promotor:0};
let sales=[],people=[],adjustments=[],bonuses=[],currentRole='Todos';
const $=id=>document.getElementById(id), n=v=>Number(v)||0;
const fmt=v=>new Intl.NumberFormat('pt-BR').format(Math.round(n(v)));
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n(v));
const key=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/\s+/g,' ').toUpperCase(); const today=()=>new Date().toISOString().slice(0,10);
const localGet=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}; const localSet=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function toast(t){const e=$('toast');if(e){e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2800)}}
function personId(role,name){return role+':'+key(name)}
function campaignDays(){const a=new Date(START+'T00:00:00'),b=new Date(today()+'T00:00:00');return Math.max(1,Math.floor((b-a)/86400000)+1)}
function rebuildPeople(){const m=new Map();sales.forEach(s=>[['Captador',s.captador],['Liner',s.liner],['Closer',s.closer]].forEach(([role,name])=>{if(name&&key(name)&&key(name)!=='NAO INFORMADO'){const id=personId(role,name);if(!m.has(id))m.set(id,{id,name:String(name).trim(),role})}}));people=[...m.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))}
function adj(p){return adjustments.find(x=>x.person_id===p.id)||{faltas:0,atrasos:0}}
function stats(p){let vgv=0,casais=0;for(const s of sales){const owner=p.role==='Captador'?s.captador:p.role==='Liner'?s.liner:s.closer;if(key(owner)!==key(p.name))continue;if(/CANCEL|INATIV|CANCELAD/i.test(String(s.status||'')))continue;vgv+=n(s.vgv);casais++}const a=adj(p),max=campaignDays()*DAY_XP;const pres=Math.max(0,max-n(a.faltas)*DAY_XP),pont=Math.max(0,max-n(a.atrasos)*DAY_XP);const xpProd=Math.round(vgv/1000*(RATE[p.role]||0));const xpBonus=bonuses.filter(x=>x.person_id===p.id).reduce((z,x)=>z+n(x.xp),0);return {...p,vgv,casais,xpProd,xpPresenca:pres,xpPontualidade:pont,xpDisc:pres+pont,xpBonus,faltas:n(a.faltas),atrasos:n(a.atrasos),xp:xpProd+pres+pont+xpBonus}}
function ranking(role=currentRole){return people.filter(p=>role==='Todos'||p.role===role).map(stats).sort((a,b)=>b.xp-a.xp||b.vgv-a.vgv||a.name.localeCompare(b.name,'pt-BR'))}
function render(){const r=ranking();$('sourceInfo').textContent=CFG.url?'🟢 Supabase configurado • campanha desde 01/07/2026':'🟠 Modo local • campanha desde 01/07/2026';const totalV=r.reduce((a,x)=>a+x.vgv,0),totalXP=r.reduce((a,x)=>a+x.xp,0);$('cards').innerHTML=[['PROFISSIONAIS',r.length],['VGV',money(totalV)],['XP TOTAL',fmt(totalXP)],['REGISTROS',fmt(sales.length)],['XP DISCIPLINA',fmt(r.reduce((a,x)=>a+x.xpDisc,0))],['FALTAS',fmt(r.reduce((a,x)=>a+x.faltas,0))]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('');$('top3').innerHTML=r.slice(0,3).map((p,i)=>`<div class="podium ${i===0?'first':''}"><div class="medal">${['🥇','🥈','🥉'][i]}</div><div class="pname">${p.name}</div><div class="muted">${p.role}</div><div class="bigxp">${fmt(p.xp)} XP</div></div>`).join('')||'<div class="notice">Nenhum resultado.</div>';$('preview').innerHTML=r.slice(0,10).map((p,i)=>`<div class="row" style="padding:9px 0;border-bottom:1px solid #202020"><span>${i+1}. ${p.name}<small class="muted"> • ${p.role}</small></span><b>${fmt(p.xp)} XP</b></div>`).join('')||'<div class="notice">Nenhum resultado.</div>';const opts=people.map(p=>`<option value="${p.id}">${p.name} — ${p.role}</option>`).join('');['focusPerson','evoPerson','adminPerson'].forEach(id=>{const e=$(id);if(e){const old=e.value;e.innerHTML=opts;e.value=old&&[...e.options].some(o=>o.value===old)?old:(people[0]?.id||'')}});renderFocus();renderRanking();renderPresence();renderAdmin();renderMonthly();renderEvolution()}
function renderFocus(){const id=$('focusPerson')?.value,r=ranking(),i=r.findIndex(p=>p.id===id);if(i<0){$('focus').innerHTML='<div class="notice">Selecione um profissional.</div>';return}const p=r[i],above=r[i-1];$('focus').innerHTML=`<div class="metricgrid"><div class="metric">Posição<b>#${i+1}</b></div><div class="metric">XP total<b>${fmt(p.xp)}</b></div><div class="metric">VGV<b>${money(p.vgv)}</b></div><div class="metric">Presença<b>${fmt(p.xpPresenca)}</b></div><div class="metric">Pontualidade<b>${fmt(p.xpPontualidade)}</b></div><div class="metric">Faltas / Atrasos<b>${p.faltas} / ${p.atrasos}</b></div></div><div class="notice" style="margin-top:10px">${above?`Faltam <b>${fmt(Math.max(0,above.xp-p.xp+1))} XP</b> para ultrapassar ${above.name}.`:'Você está no TOP 1 🏆'}</div>`}
function renderRanking(){const rr=$('rankRole')?.value||currentRole,q=key($('search')?.value||''),all=ranking(rr),r=all.filter(p=>!q||key(p.name).includes(q));$('rankingTable').innerHTML=r.map(p=>{const pos=all.findIndex(x=>x.id===p.id);return `<tr><td>${pos+1}</td><td>${pos<3?['🥇','🥈','🥉'][pos]:'—'}</td><td><b>${p.name}</b></td><td>${p.role}</td><td>${money(p.vgv)}</td><td>${p.casais}</td><td>${fmt(p.xpProd)}</td><td>${fmt(p.xpDisc)}</td><td>${fmt(p.xpBonus)}</td><td><b>${fmt(p.xp)}</b></td><td>${p.faltas}</td></tr>`}).join('')}
function renderMonthly(){const now=today().slice(0,7);const r=ranking().map(p=>({...p,monthBonus:bonuses.filter(x=>x.person_id===p.id&&String(x.event_date).startsWith(now)).reduce((z,x)=>z+n(x.xp),0)})).sort((a,b)=>b.xp-a.xp);$('monthTable').innerHTML=r.map((p,i)=>`<tr><td>${i+1}</td><td>${p.name}</td><td>${p.role}</td><td>${fmt(p.xpDisc)}</td><td>${fmt(p.monthBonus)}</td><td><b>${fmt(p.xp)}</b></td></tr>`).join('')}
function renderEvolution(){const id=$('evoPerson')?.value;if(!id)return;const p=stats(people.find(x=>x.id===id));$('evoSummary').innerHTML=`<div class="metricgrid"><div class="metric">VGV<b>${money(p.vgv)}</b></div><div class="metric">XP produção<b>${fmt(p.xpProd)}</b></div><div class="metric">XP disciplina<b>${fmt(p.xpDisc)}</b></div><div class="metric">XP bônus<b>${fmt(p.xpBonus)}</b></div></div>`;$('evoLog').innerHTML=`<div class="log-item">Desde 01/07/2026 • ${p.faltas} falta(s) • ${p.atrasos} atraso(s) • <b>${fmt(p.xp)} XP</b></div>`}
function renderPresence(){const d=$('attDate')?.value||today();$('attTable').innerHTML=people.map(p=>{const a=adj(p),s=stats(p);return `<tr><td>${p.name}</td><td>${p.role}</td><td>${a.faltas?'❌ '+a.faltas+' falta(s)':'✅ Completa'}</td><td>${a.atrasos?'⌛ '+a.atrasos+' atraso(s)':'✅ Completa'}</td><td>${fmt(s.xpDisc)}</td></tr>`}).join('')}
function renderAdmin(){const p=people.find(x=>x.id===($('adminPerson')?.value||''));if(!p)return;const a=adj(p);if($('adminFaltas'))$('adminFaltas').value=a.faltas;if($('adminAtrasos'))$('adminAtrasos').value=a.atrasos;$('adminLog').innerHTML=ranking().map(p=>{const a=adj(p);return `<div class="log-item"><b>${p.name}</b> • ${p.role} • Faltas: ${a.faltas} • Atrasos: ${a.atrasos} • Disciplina: ${fmt(p.xpDisc)} XP</div>`}).join('')}
async function api(table,method='GET',body=null,query=''){if(!CFG.url||!CFG.anonKey)throw Error('Supabase não configurado');const r=await fetch(CFG.url.replace(/\/$/,'')+'/rest/v1/'+table+(query?'?'+query:''),{method,headers:{apikey:CFG.anonKey,Authorization:'Bearer '+CFG.anonKey,'Content-Type':'application/json',Prefer:'return=representation'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.status===204?[]:await r.json()}
async function saveAdjustments(){const p=people.find(x=>x.id===($('adminPerson')?.value||''));if(!p)return;const row={person_id:p.id,person_name:p.name,role:p.role,faltas:Math.max(0,n($('adminFaltas').value)),atrasos:Math.max(0,n($('adminAtrasos').value)),updated_at:new Date().toISOString()};adjustments=adjustments.filter(x=>x.person_id!==p.id);adjustments.push(row);localSet('arena_adjustments',adjustments);if(CFG.url&&CFG.anonKey){try{await api('xp_adjustments','POST',row)}catch(e){toast('Supabase: '+e.message);return}}render();toast('Faltas e atrasos atualizados')}
async function addBonus(){const p=people.find(x=>x.id===($('adminPerson')?.value||'')),x=n($('bonusXp').value),reason=$('bonusReason').value.trim();if(!p||!x||!reason)return toast('Preencha XP e motivo');const row={person_id:p.id,person_name:p.name,role:p.role,event_date:$('adminDate').value||today(),xp:x,reason};bonuses.push(row);localSet('arena_bonuses',bonuses);if(CFG.url&&CFG.anonKey)try{await api('xp_bonuses','POST',row)}catch(e){toast('Supabase: '+e.message)}$('bonusXp').value='';$('bonusReason').value='';render();toast('Bônus adicionado')}
function parseCSV(text){const delim=(text.split(/\r?\n/)[0].match(/;/g)||[]).length>(text.split(/\r?\n/)[0].match(/,/g)||[]).length?';':',';const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],nx=text[i+1];if(c==='"'&&q&&nx==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===delim&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nx==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function cleanHeader(s){return key(s).replace(/^\uFEFF/,'')}
function normDate(v){v=String(v||'').trim();let m=v.match(/(\d{2})[\/-](\d{2})[\/-](\d{4})/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=v.match(/(\d{4})-(\d{2})-(\d{2})/);return m?m[0]:''}
function valMoney(v){return Number(String(v||'0').replace(/[^0-9,.-]/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'))||0}
async function importFile(file){const rows=parseCSV(await file.text());if(!rows.length)return toast('CSV vazio');const head=rows.shift().map(cleanHeader);const data=rows.map(r=>Object.fromEntries(head.map((h,i)=>[h,String(r[i]??'').trim()] )));const get=(o,...ks)=>{for(const k of ks){const v=o[cleanHeader(k)];if(v!==undefined)return v}return ''};const mapped=data.map((x,i)=>{const date=normDate(get(x,'DATA DE ATENDIMENTO','DATA/HORA DO CADASTRO'));return{sale_date:date,captador:get(x,'CAPTADOR','PROMOTOR DE MARKETING'),promoter:get(x,'PROMOTOR DE MARKETING'),liner:get(x,'LINER'),closer:get(x,'CLOSER'),vgv:valMoney(get(x,'VALOR VENDIDO')),status:get(x,'STATUS DO CONTRATO'),source_key:[i,date,get(x,'NOME 1'),get(x,'NOME 2'),get(x,'VALOR VENDIDO')].join('|')}}).filter(x=>x.sale_date&&x.sale_date>=START);if(!mapped.length)return toast('Nenhum registro com data a partir de 01/07/2026');sales=mapped;localSet('arena_sales',sales);rebuildPeople();if(CFG.url&&CFG.anonKey){try{await api('xp_sales','POST',mapped)}catch(e){toast('Importado localmente; Supabase: '+e.message)}}render();toast(`${mapped.length} registros importados desde 01/07/2026`)}
async function load(){sales=localGet('arena_sales',[]);adjustments=localGet('arena_adjustments',[]);bonuses=localGet('arena_bonuses',[]);if(CFG.url&&CFG.anonKey){try{const [s,a,b]=await Promise.all([api('xp_sales','GET',null,'select=*'),api('xp_adjustments','GET',null,'select=*'),api('xp_bonuses','GET',null,'select=*')]);if(s?.length)sales=s;if(a)adjustments=a;if(b)bonuses=b}catch(e){console.warn(e)}}rebuildPeople();render()}
window.setStatus=()=>{};window.setFullDay=()=>{};window.addBonus=addBonus;
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(b.dataset.view).classList.remove('hidden');document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>{currentRole=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}));['rankRole','search','focusPerson','evoPerson'].forEach(id=>$(id)?.addEventListener('input',render));$('adminPerson')?.addEventListener('change',renderAdmin);$('attDate')?.addEventListener('change',renderPresence);$('saveAdjustments')?.addEventListener('click',saveAdjustments);$('dataFile')?.addEventListener('change',e=>e.target.files[0]&&importFile(e.target.files[0]));$('attDate').value=today();$('adminDate').value=today()}
bind();load();
})();